### PR TITLE
Add PowerShell support

### PR DESCRIPTION
**Pull request by brouwers-tiobe**
See [#35209](https://redmine.tiobe.com/issues/35209). This PR brings PowerShell support forward to CPD 7.6.0.

### CODE REVIEW

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_4/Package%20CPD%20checker/run_12/attempt_2/CPD-0.1.0+273.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_4/Package%20CPD%20checker/run_13/attempt_1/CPD-0.1.0+273.zip)|

**Review by wener-tiobe — APPROVED** [review]

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_4/Package%20CPD%20checker/run_16/attempt_1/CPD-0.1.0+273.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_4/Package%20CPD%20checker/run_21/attempt_1/CPD-0.1.0+273.zip)|

**Pull request merged**
