### PR TITLE
Add possibility to exclude array initializations

### PR DESCRIPTION
**Pull request by brouwers-tiobe**
See [PR34422](https://redmine.tiobe.com/issues/34422).

This adds the ability to exclude array initializations in C/C++ from duplication. Specifically, ```{}``` -delimited comma-separated lists that directly follow an assignment (```=```) are skipped.

Rather than adding yet another variant of the --ignore-sequences/--ignore-literal-sequences flag, the --ignore-sequences option now optionally takes a parameter (one of 'literals', 'literals-identifiers', 'initializations'). If no parameter is provided, it behaves the same as the original --ignore-sequences flag, ignoring sequences of literals and identifiers.

### CODE REVIEW

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_6/Package%20CPD%20checker/run_27/attempt_1/CPD-0.1.0+273.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_6/Package%20CPD%20checker/run_30/attempt_1/CPD-0.1.0+273.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_6/Package%20CPD%20checker/run_31/attempt_1/CPD-0.1.0+273.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_6/Package%20CPD%20checker/run_32/attempt_1/CPD-0.1.0+273.zip)|

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_6/Package%20CPD%20checker/run_33/attempt_1/CPD-0.1.0+273.zip)|

**Review by wener-tiobe — APPROVED** [review]

**Comment by it-tiobe** [comment]
## Build artifact: CPD
  |Tool|Download|
  |---|---|
  |CPD|[CPD-0.1.0+273.zip](https://artifacts.tiobe.com/repository/github-artifacts/tiobe/CPD/PR_6/Package%20CPD%20checker/run_34/attempt_1/CPD-0.1.0+273.zip)|

**Pull request merged**
